### ISSUE TITLE
Make Julia v1.1+ only?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/QuasiArrays.jl#3]
@jagot any opinions? It's probably not too hard to support Julia v1.0, but not sure its worth the effort.

**Comment by jagot** [comment]
No, I don't mind since I'm most likely the only one to use my *Quasi.jl codes at the moment, and I'm on v1.1.

**Comment by dlfivefifty** [comment]
Ok, I'll go ahead. We can add Julia v1.0 support later if needed.
