### ISSUE TITLE
checkeltype_adjoint no longer in Base.LinearAlgebra

### ISSUE THREAD

**Issue by jagot** [JuliaApproximation/QuasiArrays.jl#67]
I noticed that Atoms.jl started to fail on master due to `checkeltype_adjoint` no longer being present in `Base.LinearAlgebra` (see this PR: https://github.com/JuliaLang/julia/pull/40567).

**Comment by dlfivefifty** [comment]
I don’t support master until it’s a rc

**Comment by jagot** [comment]
This is probably fixed in #77

**Comment by dlfivefifty** [comment]
Yes it is
